/*
* generated by Xtext
*/
package example.components.simple;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SimplifiedADLStandaloneSetup extends SimplifiedADLStandaloneSetupGenerated{

	public static void doSetup() {
		new SimplifiedADLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

