/*
 * generated by Xtext
 */
package example.components.simple;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SimplifiedADLRuntimeModule extends example.components.simple.AbstractSimplifiedADLRuntimeModule {

}
