/*
 * generated by Xtext
 */
package example.interfaces.simple.ui.contentassist

import example.interfaces.simple.ui.contentassist.AbstractSimplifiedItfProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class SimplifiedItfProposalProvider extends AbstractSimplifiedItfProposalProvider {
}
