/*
 * generated by Xtext
 */
package example.interfaces.simple.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import example.interfaces.simple.ui.internal.SimplifiedItfActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SimplifiedItfExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SimplifiedItfActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SimplifiedItfActivator.getInstance().getInjector(SimplifiedItfActivator.EXAMPLE_INTERFACES_SIMPLE_SIMPLIFIEDITF);
	}
	
}
