/*
 * generated by Xtext
 */
package example.interfaces.simple;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SimplifiedItfRuntimeModule extends example.interfaces.simple.AbstractSimplifiedItfRuntimeModule {

}
