/*
* generated by Xtext
*/
package example.components.simple.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SimplifiedADLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("example/components/simple/parser/antlr/internal/InternalSimplifiedADL.tokens");
	}
}
