/*
* generated by Xtext
*/
package example.components.simple.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import example.components.simple.services.SimplifiedADLGrammarAccess;

public class SimplifiedADLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SimplifiedADLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected example.components.simple.parser.antlr.internal.InternalSimplifiedADLParser createParser(XtextTokenStream stream) {
		return new example.components.simple.parser.antlr.internal.InternalSimplifiedADLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Definition";
	}
	
	public SimplifiedADLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SimplifiedADLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
