/*
 * generated by Xtext
 */
package example.components.simple.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SimplifiedADLUiModule extends example.components.simple.ui.AbstractSimplifiedADLUiModule {
	public SimplifiedADLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
