/*
* generated by Xtext
*/
package example.interfaces.simple.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SimplifiedItfAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("example/interfaces/simple/parser/antlr/internal/InternalSimplifiedItf.tokens");
	}
}
