/*
* generated by Xtext
*/
package example.interfaces.simple.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import example.interfaces.simple.services.SimplifiedItfGrammarAccess;

public class SimplifiedItfParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SimplifiedItfGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected example.interfaces.simple.parser.antlr.internal.InternalSimplifiedItfParser createParser(XtextTokenStream stream) {
		return new example.interfaces.simple.parser.antlr.internal.InternalSimplifiedItfParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "InterfaceDefinition";
	}
	
	public SimplifiedItfGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SimplifiedItfGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
