/*
 * generated by Xtext
 */
package example.interfaces.simple.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SimplifiedItfUiModule extends example.interfaces.simple.ui.AbstractSimplifiedItfUiModule {
	public SimplifiedItfUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
