/*
* generated by Xtext
*/
package example.interfaces.simple.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import example.interfaces.simple.services.SimplifiedItfGrammarAccess;

public class SimplifiedItfParser extends AbstractContentAssistParser {
	
	@Inject
	private SimplifiedItfGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected example.interfaces.simple.ui.contentassist.antlr.internal.InternalSimplifiedItfParser createParser() {
		example.interfaces.simple.ui.contentassist.antlr.internal.InternalSimplifiedItfParser result = new example.interfaces.simple.ui.contentassist.antlr.internal.InternalSimplifiedItfParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
					put(grammarAccess.getInterfaceDefinitionAccess().getGroup(), "rule__InterfaceDefinition__Group__0");
					put(grammarAccess.getMethodAccess().getGroup(), "rule__Method__Group__0");
					put(grammarAccess.getMethodAccess().getGroup_4(), "rule__Method__Group_4__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getInterfaceDefinitionAccess().getNameAssignment_1(), "rule__InterfaceDefinition__NameAssignment_1");
					put(grammarAccess.getInterfaceDefinitionAccess().getMethodsAssignment_3(), "rule__InterfaceDefinition__MethodsAssignment_3");
					put(grammarAccess.getMethodAccess().getReturnTypeAssignment_0(), "rule__Method__ReturnTypeAssignment_0");
					put(grammarAccess.getMethodAccess().getNameAssignment_1(), "rule__Method__NameAssignment_1");
					put(grammarAccess.getMethodAccess().getTypesListAssignment_3(), "rule__Method__TypesListAssignment_3");
					put(grammarAccess.getMethodAccess().getTypesListAssignment_4_1(), "rule__Method__TypesListAssignment_4_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			example.interfaces.simple.ui.contentassist.antlr.internal.InternalSimplifiedItfParser typedParser = (example.interfaces.simple.ui.contentassist.antlr.internal.InternalSimplifiedItfParser) parser;
			typedParser.entryRuleInterfaceDefinition();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public SimplifiedItfGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SimplifiedItfGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
