/*
 * generated by Xtext
 */
package example.components.simple.ui.contentassist

import example.components.simple.ui.contentassist.AbstractSimplifiedADLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class SimplifiedADLProposalProvider extends AbstractSimplifiedADLProposalProvider {
}
